import { Worker } from 'bullmq';
import { connection } from '../queues/connection';
import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import fs from 'fs';

const execPromise = util.promisify(exec);

export const compressWorker = new Worker(
  'compress',
  async (job) => {
    const { fileId, filename, uploadPath, quality } = job.data;
    
    // Determine Ghostscript quality setting
    // screen = low quality / high compression
    // ebook = medium quality / medium compression
    // printer = high quality / low compression
    let gsQuality = 'ebook';
    if (quality === 'low') gsQuality = 'screen';
    if (quality === 'high') gsQuality = 'printer';

    const outFilename = `compressed-${filename}`;
    const outPath = path.join(process.cwd(), 'uploads', outFilename);

    // Run Ghostscript command
    const gsCommand = `gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/${gsQuality} -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${outPath}" "${uploadPath}"`;
    
    await job.updateProgress(10);
    
    try {
      await execPromise(gsCommand);
      await job.updateProgress(90);

      // Verify the output file exists
      if (!fs.existsSync(outPath)) {
        throw new Error('Output file was not generated by Ghostscript.');
      }

      // Cleanup original upload
      fs.unlinkSync(uploadPath);

      await job.updateProgress(100);
      return { filename: outFilename };
    } catch (error: any) {
      console.error('Compression error:', error);
      throw new Error(`Compression failed: ${error.message}`);
    }
  },
  { connection }
);

compressWorker.on('completed', (job) => {
  console.log(`Job ${job.id} completed! Result:`, job.returnvalue);
});

compressWorker.on('failed', (job, err) => {
  console.error(`Job ${job?.id} failed with ${err.message}`);
});
