import { Worker } from 'bullmq';
import { connection } from '../queues/connection';
import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import fs from 'fs';

const execPromise = util.promisify(exec);

export const convertWorker = new Worker(
  'convert',
  async (job) => {
    const { fileId, filename, uploadPath, targetFormat } = job.data;
    
    // Security measure: validate target format to prevent command injection
    const allowedFormats = ['pdf', 'docx', 'xlsx', 'pptx', 'html', 'txt'];
    if (!allowedFormats.includes(targetFormat)) {
      throw new Error(`Unsupported target format: ${targetFormat}`);
    }

    const outdir = path.join(process.cwd(), 'uploads');

    // Run LibreOffice headless conversion
    // e.g. libreoffice --headless --convert-to docx "/path/to/file.pdf" --outdir "/path/to/outdir"
    const command = `libreoffice --headless --convert-to ${targetFormat} "${uploadPath}" --outdir "${outdir}"`;
    
    await job.updateProgress(10);
    
    try {
      await execPromise(command);
      await job.updateProgress(90);

      // LibreOffice names the output file same as input but different extension
      const basename = path.parse(filename).name;
      const expectedOutFilename = `${basename}.${targetFormat}`;
      const outPath = path.join(outdir, expectedOutFilename);

      if (!fs.existsSync(outPath)) {
        throw new Error('Output file was not generated by LibreOffice.');
      }

      // Cleanup original upload
      fs.unlinkSync(uploadPath);

      await job.updateProgress(100);
      return { filename: expectedOutFilename };
    } catch (error: any) {
      console.error('Conversion error:', error);
      throw new Error(`Conversion failed: ${error.message}`);
    }
  },
  { connection }
);

convertWorker.on('completed', (job) => {
  console.log(`Job ${job.id} completed! Result:`, job.returnvalue);
});

convertWorker.on('failed', (job, err) => {
  console.error(`Job ${job?.id} failed with ${err.message}`);
});
