import { Worker } from 'bullmq';
import { connection } from '../queues/connection';
import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import fs from 'fs';

const execPromise = util.promisify(exec);

export const convertWorker = new Worker(
  'convert',
  async (job) => {
    const { fileId, filename, uploadPath, targetFormat } = job.data;
    
    // Security measure: validate target format to prevent command injection
    const allowedFormats = ['pdf', 'docx', 'xlsx', 'pptx', 'html', 'txt'];
    if (!allowedFormats.includes(targetFormat)) {
      throw new Error(`Unsupported target format: ${targetFormat}`);
    }

    const outdir = path.join(process.cwd(), 'uploads');
    const ext = path.extname(filename).toLowerCase();

    await job.updateProgress(10);
    
    try {
      let command = '';
      let tempFilesToCleanup: string[] = [];

      if (ext === '.pdf') {
        // PDF to Office Formats
        if (targetFormat === 'docx') {
          command = `libreoffice --headless --infilter="writer_pdf_import" --convert-to docx "${uploadPath}" --outdir "${outdir}"`;
        } else if (targetFormat === 'pptx') {
          command = `libreoffice --headless --infilter="impress_pdf_import" --convert-to pptx "${uploadPath}" --outdir "${outdir}"`;
        } else if (targetFormat === 'txt') {
          command = `libreoffice --headless --infilter="writer_pdf_import" --convert-to txt "${uploadPath}" --outdir "${outdir}"`;
        } else if (targetFormat === 'html') {
          command = `libreoffice --headless --infilter="writer_pdf_import" --convert-to html "${uploadPath}" --outdir "${outdir}"`;
        } else if (targetFormat === 'xlsx') {
          // PDF to Excel: Convert to HTML first, then HTML to XLSX
          const basename = path.parse(filename).name;
          const generatedHtmlPath = path.join(outdir, `${basename}.html`);
          tempFilesToCleanup.push(generatedHtmlPath);

          const firstCmd = `libreoffice --headless --infilter="writer_pdf_import" --convert-to html "${uploadPath}" --outdir "${outdir}"`;
          await execPromise(firstCmd);
          await job.updateProgress(50);

          command = `libreoffice --headless --convert-to xlsx "${generatedHtmlPath}" --outdir "${outdir}"`;
        }
      } else {
        // Office Formats (DOCX, XLSX, PPTX, etc.) to PDF
        command = `libreoffice --headless --convert-to pdf "${uploadPath}" --outdir "${outdir}"`;
      }

      await execPromise(command);
      await job.updateProgress(90);

      // LibreOffice names the output file same as input but different extension
      const basename = path.parse(filename).name;
      const expectedOutFilename = `${basename}.${targetFormat}`;
      const outPath = path.join(outdir, expectedOutFilename);

      if (!fs.existsSync(outPath)) {
        throw new Error('Output file was not generated by LibreOffice.');
      }

      // Cleanup original upload and any temp files
      if (fs.existsSync(uploadPath)) {
        fs.unlinkSync(uploadPath);
      }
      for (const tempFile of tempFilesToCleanup) {
        if (fs.existsSync(tempFile)) {
          fs.unlinkSync(tempFile);
        }
      }

      await job.updateProgress(100);
      return { filename: expectedOutFilename };
    } catch (error: any) {
      console.error('Conversion error:', error);
      throw new Error(`Conversion failed: ${error.message}`);
    }
  },
  { connection: connection as any }
);

convertWorker.on('completed', (job) => {
  console.log(`Job ${job.id} completed! Result:`, job.returnvalue);
});

convertWorker.on('failed', (job, err) => {
  console.error(`Job ${job?.id} failed with ${err.message}`);
});
