import { Worker } from 'bullmq';
import { connection } from '../queues/connection';
import { exec } from 'child_process';
import util from 'util';
import path from 'path';
import fs from 'fs';

const execPromise = util.promisify(exec);

export const ocrWorker = new Worker(
  'ocr',
  async (job) => {
    const { fileId, filename, uploadPath, language } = job.data;
    
    // Tesseract expects an output base name without extension, and will append .pdf itself when generating a PDF
    const outBasename = `ocr-${fileId}`;
    const outPathPrefix = path.join(process.cwd(), 'uploads', outBasename);
    
    // Validate language
    const allowedLangs = ['eng', 'hin', 'spa', 'fra', 'deu', 'jpn', 'chi_sim'];
    const safeLang = allowedLangs.includes(language) ? language : 'eng';

    // Run Tesseract to output a PDF with text overlay
    // tesseract input.pdf output_base_name -l eng pdf
    const command = `tesseract "${uploadPath}" "${outPathPrefix}" -l ${safeLang} pdf`;
    
    await job.updateProgress(10);
    
    try {
      await execPromise(command);
      await job.updateProgress(90);

      const expectedOutFilename = `${outBasename}.pdf`;
      const outPath = path.join(process.cwd(), 'uploads', expectedOutFilename);

      if (!fs.existsSync(outPath)) {
        throw new Error('Output file was not generated by Tesseract.');
      }

      // Cleanup original upload
      fs.unlinkSync(uploadPath);

      await job.updateProgress(100);
      return { filename: expectedOutFilename };
    } catch (error: any) {
      console.error('OCR error:', error);
      throw new Error(`OCR failed: ${error.message}`);
    }
  },
  { connection }
);

ocrWorker.on('completed', (job) => {
  console.log(`Job ${job.id} completed! Result:`, job.returnvalue);
});

ocrWorker.on('failed', (job, err) => {
  console.error(`Job ${job?.id} failed with ${err.message}`);
});
